-- M_USER 用户管理模块表结构。
-- 目标数据库: MySQL 8.x

CREATE TABLE IF NOT EXISTS M_USER (
    ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    TENANT_ID VARCHAR(36) NULL COMMENT '租户标识',
    USERNAME VARCHAR(50) NOT NULL COMMENT '登录用户名',
    DISPLAY_NAME VARCHAR(100) NULL COMMENT '显示名称',
    EMAIL VARCHAR(100) NULL COMMENT '邮箱',
    EMAIL_VERIFIED TINYINT NOT NULL DEFAULT 0 COMMENT '邮箱验证标记: 0/1',
    PHONE VARCHAR(30) NULL COMMENT '手机号',
    PHONE_VERIFIED TINYINT NOT NULL DEFAULT 0 COMMENT '手机号验证标记: 0/1',
    PASSWORD_HASH VARCHAR(100) NOT NULL COMMENT 'BCrypt 密码哈希',
    PASSWORD_CHANGED_AT DATETIME NULL COMMENT '密码最近修改时间 (UTC)',
    STATUS TINYINT NOT NULL DEFAULT 1 COMMENT '状态: 1=启用, 0=停用',
    ACCOUNT_LOCKED TINYINT NOT NULL DEFAULT 0 COMMENT '账号锁定标记: 0=未锁定, 1=已锁定',
    LOCKED_AT DATETIME NULL COMMENT '锁定时间 (UTC)',
    FAILED_LOGIN_COUNT INT NOT NULL DEFAULT 0 COMMENT '连续登录失败次数',
    LAST_LOGIN_AT DATETIME NULL COMMENT '最近登录时间 (UTC)',
    LAST_LOGIN_IP VARCHAR(64) NULL COMMENT '最近登录IP',
    LOCALE VARCHAR(20) NULL COMMENT '语言区域偏好',
    TIMEZONE VARCHAR(40) NULL COMMENT '时区偏好',
    REMARK TEXT NULL COMMENT '备注',
    VERSION INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间 (UTC)',
    CREATED_BY BIGINT NULL COMMENT '创建人用户ID',
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间 (UTC)',
    UPDATED_BY BIGINT NULL COMMENT '更新人用户ID',
    DELETED_AT DATETIME NULL COMMENT '软删除时间 (UTC)',
    PRIMARY KEY (ID),
    UNIQUE KEY uk_username (USERNAME),
    UNIQUE KEY uk_email (EMAIL),
    UNIQUE KEY uk_phone (PHONE),
    KEY idx_tenant_status (TENANT_ID, STATUS),
    KEY idx_status_locked (STATUS, ACCOUNT_LOCKED),
    KEY idx_deleted (DELETED_AT),
    KEY idx_created_by (CREATED_BY),
    KEY idx_updated_by (UPDATED_BY),
    KEY idx_username_deleted (USERNAME, DELETED_AT)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_0900_ai_ci
  COMMENT='用户主数据表';
