-- M_ROLE 角色管理表结构。
-- 目标数据库: MySQL 8.x

CREATE TABLE IF NOT EXISTS M_ROLE (
    ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    TENANT_ID VARCHAR(36) NULL COMMENT '租户标识',
    ROLE_CODE VARCHAR(50) NOT NULL COMMENT '角色编码，例如 ROLE_ADMIN',
    ROLE_NAME VARCHAR(100) NOT NULL COMMENT '角色显示名称',
    DESCRIPTION VARCHAR(255) NULL COMMENT '角色描述',
    STATUS TINYINT NOT NULL DEFAULT 1 COMMENT '状态: 1=启用, 0=停用',
    IS_SYSTEM TINYINT NOT NULL DEFAULT 0 COMMENT '系统角色标记: 1=系统角色, 0=自定义',
    SORT_ORDER INT NOT NULL DEFAULT 0 COMMENT '排序值',
    REMARK TEXT NULL COMMENT '备注',
    VERSION INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间 (UTC)',
    CREATED_BY BIGINT NULL COMMENT '创建人用户ID',
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间 (UTC)',
    UPDATED_BY BIGINT NULL COMMENT '更新人用户ID',
    DELETED_AT DATETIME NULL COMMENT '软删除时间 (UTC)',
    PRIMARY KEY (ID),
    UNIQUE KEY uk_role_code (ROLE_CODE),
    KEY idx_tenant_status (TENANT_ID, STATUS),
    KEY idx_is_system (IS_SYSTEM),
    KEY idx_deleted (DELETED_AT),
    KEY idx_created_by (CREATED_BY),
    KEY idx_updated_by (UPDATED_BY)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_0900_ai_ci
  COMMENT='角色主数据表';
