-- M_PERMISSION 权限管理表结构。
-- 目标数据库: MySQL 8.x

CREATE TABLE IF NOT EXISTS M_PERMISSION (
    ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    TENANT_ID VARCHAR(36) NULL COMMENT '租户标识',
    PERMISSION_CODE VARCHAR(120) NOT NULL COMMENT '权限编码，例如 DOMAIN:RESOURCE:ACTION',
    PERMISSION_NAME VARCHAR(120) NOT NULL COMMENT '权限显示名称',
    DESCRIPTION VARCHAR(255) NULL COMMENT '权限描述',
    STATUS TINYINT NOT NULL DEFAULT 1 COMMENT '状态: 1=启用, 0=停用',
    RESOURCE_TYPE VARCHAR(20) NOT NULL DEFAULT 'API' COMMENT '资源类型: API/UI/DATA',
    RESOURCE VARCHAR(200) NOT NULL COMMENT '资源标识',
    HTTP_METHOD VARCHAR(10) NULL COMMENT 'API资源对应的 HTTP 方法',
    ACTION VARCHAR(50) NULL COMMENT '动作关键字，例如 READ/WRITE',
    PERMISSION_GROUP VARCHAR(60) NULL COMMENT '权限分组',
    SORT_ORDER INT NOT NULL DEFAULT 0 COMMENT '排序值',
    UI_MENU_KEY VARCHAR(120) NULL COMMENT '前端菜单键',
    UI_ROUTE VARCHAR(200) NULL COMMENT '前端路由',
    REMARK TEXT NULL COMMENT '备注',
    VERSION INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间 (UTC)',
    CREATED_BY BIGINT NULL COMMENT '创建人用户ID',
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间 (UTC)',
    UPDATED_BY BIGINT NULL COMMENT '更新人用户ID',
    DELETED_AT DATETIME NULL COMMENT '软删除时间 (UTC)',
    PRIMARY KEY (ID),
    UNIQUE KEY uk_permission_code (PERMISSION_CODE),
    KEY idx_tenant_status (TENANT_ID, STATUS),
    KEY idx_resource_type (RESOURCE_TYPE),
    KEY idx_resource (RESOURCE),
    KEY idx_http_method (HTTP_METHOD),
    KEY idx_action (ACTION),
    KEY idx_group (PERMISSION_GROUP),
    KEY idx_ui_menu (UI_MENU_KEY),
    KEY idx_res_method (RESOURCE, HTTP_METHOD),
    KEY idx_group_status (PERMISSION_GROUP, STATUS),
    KEY idx_deleted (DELETED_AT),
    KEY idx_created_by (CREATED_BY),
    KEY idx_updated_by (UPDATED_BY)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_0900_ai_ci
  COMMENT='权限主数据表';
