-- M_USER_ROLE 用户角色关联表结构。
-- 目标数据库: MySQL 8.x

CREATE TABLE IF NOT EXISTS M_USER_ROLE (
    USER_ID BIGINT NOT NULL COMMENT '用户ID',
    ROLE_ID BIGINT NOT NULL COMMENT '角色ID',
    TENANT_ID VARCHAR(36) NULL COMMENT '租户标识',
    IS_PRIMARY TINYINT NOT NULL DEFAULT 0 COMMENT '主角色标记',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间 (UTC)',
    CREATED_BY BIGINT NULL COMMENT '创建人用户ID',
    UPDATED_AT DATETIME NULL COMMENT '更新时间 (UTC)',
    UPDATED_BY BIGINT NULL COMMENT '更新人用户ID',
    PRIMARY KEY (USER_ID, ROLE_ID),
    UNIQUE KEY uk_tenant_user_role (TENANT_ID, USER_ID, ROLE_ID),
    KEY idx_user_id (USER_ID),
    KEY idx_role_id (ROLE_ID),
    KEY idx_tenant_user (TENANT_ID, USER_ID),
    KEY idx_created_by (CREATED_BY),
    KEY idx_updated_by (UPDATED_BY),
    CONSTRAINT fk_m_user_role_user
        FOREIGN KEY (USER_ID) REFERENCES M_USER (ID)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_m_user_role_role
        FOREIGN KEY (ROLE_ID) REFERENCES M_ROLE (ID)
        ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_0900_ai_ci
  COMMENT='用户角色关联表';
