-- M_ROLE_PERMISSION 角色权限关联表结构。
-- 目标数据库: MySQL 8.x

CREATE TABLE IF NOT EXISTS M_ROLE_PERMISSION (
    ROLE_ID BIGINT NOT NULL COMMENT '角色ID',
    PERMISSION_ID BIGINT NOT NULL COMMENT '权限ID',
    TENANT_ID VARCHAR(36) NULL COMMENT '租户标识',
    SCOPE VARCHAR(50) NULL COMMENT '权限作用域',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间 (UTC)',
    CREATED_BY BIGINT NULL COMMENT '创建人用户ID',
    UPDATED_AT DATETIME NULL COMMENT '更新时间 (UTC)',
    UPDATED_BY BIGINT NULL COMMENT '更新人用户ID',
    PRIMARY KEY (ROLE_ID, PERMISSION_ID),
    UNIQUE KEY uk_tenant_role_permission (TENANT_ID, ROLE_ID, PERMISSION_ID),
    KEY idx_role_id (ROLE_ID),
    KEY idx_perm_id (PERMISSION_ID),
    KEY idx_tenant_role (TENANT_ID, ROLE_ID),
    KEY idx_created_by (CREATED_BY),
    KEY idx_updated_by (UPDATED_BY),
    CONSTRAINT fk_m_role_permission_role
        FOREIGN KEY (ROLE_ID) REFERENCES M_ROLE (ID)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_m_role_permission_permission
        FOREIGN KEY (PERMISSION_ID) REFERENCES M_PERMISSION (ID)
        ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_0900_ai_ci
  COMMENT='角色权限关联表';
