-- M_STOCK_PRICE_HISTORY schema for stock daily price history.
-- Target: MySQL 8.x

CREATE TABLE IF NOT EXISTS `M_STOCK_PRICE_HISTORY` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `STOCK_CODE` VARCHAR(100) NOT NULL COMMENT '銘柄コード',
  `TRANS_DATE` DATE NOT NULL COMMENT '取引日付',
  `BEFORE_DAY_PRICE` INT DEFAULT NULL COMMENT '前日株価',
  `OPEN_PRICE` INT DEFAULT NULL COMMENT '始値',
  `HIGH_PRICE` INT DEFAULT NULL COMMENT '高値',
  `LOW_PRICE` INT DEFAULT NULL COMMENT '安値',
  `CLOSE_PRICE` INT DEFAULT NULL COMMENT '終値',
  `ADJUSTED_CLOSE_PRICE` INT DEFAULT NULL COMMENT '調整後終値',
  `BEFORE_DAY_DIFF` INT DEFAULT NULL COMMENT '前日比',
  `BEFORE_DAY_DIFF_PERCENT` DECIMAL(6,2) DEFAULT NULL COMMENT '前日比％',
  `VOLUME` INT DEFAULT NULL COMMENT '売買高(株)',
  `REMARK` TEXT COMMENT '備考',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `uk_stock_code_trans_date` (`STOCK_CODE`, `TRANS_DATE`),
  KEY `idx_stock_code` (`STOCK_CODE`),
  KEY `idx_trans_date` (`TRANS_DATE`),
  KEY `idx_stock_date` (`STOCK_CODE`, `TRANS_DATE`)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_bin
  COMMENT='株価履歴管理表';
