-- M_STOCK_FAVORITE schema for stock favorites list.
-- Target: MySQL 8.x

CREATE TABLE IF NOT EXISTS `M_STOCK_FAVORITE` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `STOCK_CODE` VARCHAR(100) NOT NULL COMMENT 'Stock code',
  `CREATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created at',
  `UPDATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated at',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `uk_stock_favorite_stock_code` (`STOCK_CODE`),
  KEY `idx_stock_favorite_created_at` (`CREATED_AT`),
  CONSTRAINT `fk_stock_favorite_stock_code` FOREIGN KEY (`STOCK_CODE`) REFERENCES `M_STOCK` (`STOCK_CODE`)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_bin
  COMMENT='Stock favorites';
