spring:
  application:
    name: kabu-admin-v3
  datasource:
    url: jdbc:mysql://160.16.135.58:3306/kabu_web?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: Ly$20240301
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath*:db/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8080
